import { createFileRoute } from "@tanstack/react-router";
import { BookOpen, Map, ClipboardCheck, Globe2 } from "lucide-react";
import { PageIntro, SectionHeading } from "@/components/site/sections";
import { archiveStats } from "@/data/heritage";

export const Route=createFileRoute("/about")({head:()=>({meta:[
 {title:"About the Project — Ganpati Dharohar"},{name:"description",content:"About the purpose, objective, methodology and student team behind Ganpati Dharohar."},{property:"og:title",content:"About Ganpati Dharohar"},{property:"og:description",content:"A college Community Engagement Project for digital preservation of Mumbai's Ganpati heritage."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}
]}),component:AboutPage});
const methodology=[{icon:BookOpen,label:"Research"},{icon:Map,label:"Field Visit"},{icon:ClipboardCheck,label:"Documentation"},{icon:ClipboardCheck,label:"Survey"},{icon:Globe2,label:"Digital Archive"},{icon:Globe2,label:"Awareness"}];
function AboutPage(){return <><PageIntro eyebrow="College CEP" title="About Ganpati Dharohar" description="A community-based digital heritage preservation project created to document Mumbai's Ganpati traditions through verified research, field work and public participation."/><section className="py-18"><div className="archive-container grid gap-12 lg:grid-cols-2"><div><SectionHeading eyebrow="Project" title="Ganpati Dharohar"/><dl className="mt-6 space-y-5"><div><dt className="eyebrow">Project Type</dt><dd className="mt-1 leading-7 text-foreground/85">CEP / Community Engagement Project</dd></div><div><dt className="eyebrow">Main Objective</dt><dd className="mt-1 leading-7 text-foreground/85">To digitally document, preserve and create awareness about Mumbai's Ganpati heritage through field visits, photographs, community participation and a digital archive.</dd></div><div><dt className="eyebrow">Method</dt><dd className="mt-1 leading-7 text-foreground/85">Research → Field Visit → Documentation → Survey → Digital Archive → Awareness</dd></div></dl></div><div className="archive-card p-7"><p className="eyebrow">Field work</p><dl className="mt-6 grid grid-cols-3 gap-3">{[[String(archiveStats.mandals),"Mandals visited"],[String(archiveStats.photographs),"Photographs"],["—","Survey responses"]].map(([value,label])=><div key={label} className="bg-muted p-4 text-center"><dt className="font-display text-4xl text-primary">{value}</dt><dd className="mt-2 text-[10px] font-bold uppercase tracking-[.1em] text-muted-foreground">{label}</dd></div>)}</dl><p className="mt-5 text-sm text-muted-foreground">Field visits: 17–24 September 2026 · Govandi, Chembur, Sewri</p></div></div></section><section className="border-y border-border bg-muted/45 py-20"><div className="archive-container"><SectionHeading eyebrow="Methodology" title="From research to archive"/><div className="mt-9 grid gap-4 md:grid-cols-3 lg:grid-cols-6">{methodology.map(({icon:Icon,label},i)=><article key={label} className="archive-card p-6"><span className="text-xs font-bold text-gold">0{i+1}</span><Icon className="mt-8 size-7 text-accent-foreground"/><h3 className="mt-4 font-display text-2xl text-primary">{label}</h3></article>)}</div></div></section><section className="py-20"><div className="archive-container"><SectionHeading eyebrow="Project team" title="Student contributors" description="Team details will be added when the final project information is supplied."/><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[1,2,3].map(i=><article key={i} className="border border-dashed border-border bg-card p-6"><div className="size-12 rounded-full bg-secondary"/><h3 className="mt-5 font-display text-2xl text-primary">[Student name]</h3><p className="mt-1 text-sm text-muted-foreground">[Role / contribution]</p></article>)}</div></div></section></>}
