import { createFileRoute } from "@tanstack/react-router";
import { X, ImageIcon } from "lucide-react";
import { useState } from "react";
import { PageIntro } from "@/components/site/sections";
import { Button } from "@/components/ui/button";
import { galleryItems, type GalleryCategory } from "@/data/heritage";
const filters: Array<"All"|GalleryCategory>=["All","Idols","Decorations","Traditions","Community","Eco-Friendly"];
export const Route=createFileRoute("/gallery")({head:()=>({meta:[{title:"Digital Gallery — Ganpati Dharohar"},{name:"description",content:"A visual archive prepared for verified Ganpati field photographs, traditions and community documentation."},{property:"og:title",content:"Digital Gallery — Ganpati Dharohar"},{property:"og:description",content:"Explore visual records of Ganpati art, traditions, decorations and preservation."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:GalleryPage});
function GalleryPage(){const[filter,setFilter]=useState<(typeof filters)[number]>("All");const[selected,setSelected]=useState<(typeof galleryItems)[number]|null>(null);const items=galleryItems.filter(i=>filter==="All"||i.category===filter);return <><PageIntro eyebrow="Visual records" title="Digital Gallery" description="A structured home for verified field photographs. Current images are clearly labelled illustrations and not project field work."/><section className="py-14"><div className="archive-container"><div className="flex flex-wrap gap-2">{filters.map(item=><Button key={item} size="sm" variant={filter===item?"default":"outline"} onClick={()=>setFilter(item)}>{item}</Button>)}</div>{items.length?<div className="mt-8 columns-1 gap-5 sm:columns-2 lg:columns-3">{items.map(item=><button key={item.id} className="archive-card group mb-5 w-full overflow-hidden text-left" onClick={()=>setSelected(item)}><img src={item.src} alt={item.alt} width={1200} height={900} loading="lazy" className="aspect-[4/3] w-full object-cover transition-transform duration-500 group-hover:scale-[1.02]"/><span className="block p-4"><span className="text-[10px] font-bold uppercase tracking-[.14em] text-accent-foreground">{item.category} · Illustrative placeholder</span><strong className="mt-2 block font-display text-xl text-primary">{item.caption}</strong><small className="mt-1 block text-muted-foreground">{item.mandal}</small></span></button>)}</div>:<div className="mt-10 py-16 text-center"><ImageIcon className="mx-auto text-muted-foreground"/><p className="mt-3">No gallery images in this category yet.</p></div>}</div></section>{selected&&<div className="fixed inset-0 z-[70] flex items-center justify-center bg-foreground/85 p-4" role="dialog" aria-modal="true" aria-label="Image preview" onClick={()=>setSelected(null)}><div className="relative max-w-5xl" onClick={(e)=>e.stopPropagation()}><Button size="icon" variant="secondary" className="absolute right-3 top-3 z-10" onClick={()=>setSelected(null)} aria-label="Close preview"><X/></Button><img src={selected.src} alt={selected.alt} width={1200} height={900} className="max-h-[78vh] w-auto rounded-md object-contain"/><div className="bg-card p-4"><strong className="font-display text-xl text-primary">{selected.caption}</strong><p className="text-xs text-muted-foreground">Illustrative placeholder — replace with verified field photography.</p></div></div></div>}</>}
