import { createFileRoute, Link } from "@tanstack/react-router";
import { BookOpen, Brush, Users, Leaf, ArrowRight, Landmark, Camera, ScrollText, ClipboardList } from "lucide-react";
import { Button } from "@/components/ui/button";
import { MandalCard, ProcessLine, SectionHeading } from "@/components/site/sections";
import { mandals, archiveStats } from "@/data/heritage";
import { methodSteps, preservationSteps } from "@/data/site";
import heroImage from "@/assets/images/field/f-010-013.jpg";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "Ganpati Dharohar — Mumbai Ganpati Heritage Archive" },
    { name: "description", content: "A student-led digital archive documenting Mumbai's Ganpati heritage, community traditions and preservation." },
    { property: "og:title", content: "Ganpati Dharohar — Mumbai Ganpati Heritage Archive" },
    { property: "og:description", content: "Document, digitize and preserve Mumbai's Ganpati heritage." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ]}), component: HomePage,
});

const preserve = [
  { icon: BookOpen, title: "Traditions", text: "Document traditional Ganpati customs and practices." },
  { icon: Brush, title: "Art & Idols", text: "Highlight idol-making, artwork and decoration." },
  { icon: Users, title: "Community", text: "Document community participation and activities." },
  { icon: Leaf, title: "Eco-Friendly Practices", text: "Highlight environmentally responsible celebration practices." },
];

function HomePage() {
  return <>
    <section className="relative min-h-[76vh] overflow-hidden bg-primary text-primary-foreground">
      <img src={heroImage} alt="Ganpati idol at Shivdi Cha Raja Ganpati Mandal, Sewri" width={1600} height={1000} className="absolute inset-0 size-full object-cover object-center" />
      <div className="absolute inset-0 bg-primary/45" /><div className="absolute inset-y-0 left-0 w-full bg-gradient-to-r from-primary via-primary/85 to-transparent lg:w-3/4" />
      <div className="archive-container relative flex min-h-[76vh] items-center py-20"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-gold-light">Preserving Mumbai's Ganpati Heritage</p><h1 className="mt-5 font-display text-6xl leading-[.95] md:text-8xl">Ganpati<br />Dharohar</h1><p className="mt-6 max-w-xl text-base leading-8 text-primary-foreground/85 md:text-lg">Discover the stories, traditions, art and community heritage behind Mumbai's Ganpati celebrations.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg" className="bg-secondary text-secondary-foreground hover:bg-secondary/90"><Link to="/explore">Explore Heritage <ArrowRight /></Link></Button><Button asChild size="lg" variant="outline" className="border-primary-foreground/45 bg-primary/20 text-primary-foreground hover:bg-primary-foreground/10 hover:text-primary-foreground"><Link to="/survey">Community Survey</Link></Button></div><p className="mt-6 text-xs text-primary-foreground/65">Field photograph · Shivdi Cha Raja, Sewri · 18 September 2026</p></div></div>
    </section>
    <section className="py-20"><div className="archive-container grid gap-10 lg:grid-cols-2 lg:items-center"><SectionHeading eyebrow="About the project" title="About Ganpati Dharohar" /><p className="leading-8 text-muted-foreground">Ganpati Dharohar is a college Community Engagement Project (CEP) that documents Mumbai's Ganpati mandals through field visits, photographs and observations, and presents them as a digital heritage archive that anyone can explore. <Link to="/about" className="font-semibold text-primary underline-offset-4 hover:underline">Read more</Link></p></div></section>
    <section className="pattern-line py-20"><div className="archive-container"><SectionHeading eyebrow="Living heritage" title="What We Preserve" description="A cultural archive is more than a collection of images. It records the knowledge, creativity and shared work behind the celebration." /><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{preserve.map(({icon: Icon, title, text}) => <article key={title} className="archive-card p-6"><Icon className="size-7 text-accent-foreground" /><h3 className="mt-8 font-display text-2xl text-primary">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div></div></section>
    <section className="border-y border-border bg-muted/45 py-20"><div className="archive-container"><div className="flex flex-wrap items-end justify-between gap-6"><SectionHeading eyebrow="Archive entries" title="Explore Mumbai's Ganpati Heritage" description="Five mandals documented through field visits across Govandi, Chembur and Sewri." /><Button asChild variant="outline"><Link to="/explore">View all entries <ArrowRight /></Link></Button></div><div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{mandals.map((mandal) => <MandalCard key={mandal.id} mandal={mandal} />)}</div></div></section>
    <section className="py-20"><div className="archive-container"><SectionHeading eyebrow="Archive" title="Our Heritage Documentation" description="This project documents Ganpati mandals through field visits, photographs, observations and community participation, creating a digital record of Mumbai's living Ganpati heritage." /><div className="mt-10 grid gap-4 md:grid-cols-3">{[{icon:Landmark,title:"Mandals Documented",text:"Information about the Ganpati mandals visited and documented during the CEP fieldwork.",to:"/explore"},{icon:Camera,title:"Field Photographs",text:"Original photographs collected during field visits, including Ganpati idols, pandals, decorations and other observations.",to:"/gallery"},{icon:ScrollText,title:"Heritage Stories",text:"Stories, traditions, cultural practices and observations recorded from the documented mandals.",to:"/explore"}].map(({icon:Icon,title,text,to}) => <Link key={title} to={to} className="archive-card block p-6 transition-transform hover:-translate-y-1"><Icon className="size-7 text-accent-foreground" /><h3 className="mt-8 font-display text-2xl text-primary">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></Link>)}</div></div></section>
    <section className="py-20"><div className="archive-container"><SectionHeading eyebrow="Project method" title="From field research to public awareness" /><ProcessLine steps={methodSteps} /></div></section>
    <section className="bg-surface-deep py-20 text-primary-foreground"><div className="archive-container"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-gold-light">Project impact</p><h2 className="mt-3 font-display text-3xl text-primary-foreground md:text-5xl">Our Field Documentation</h2><p className="mt-4 leading-7 text-primary-foreground/90">A record of the Ganpati mandals, photographs and heritage information documented through our CEP fieldwork.</p></div><div className="mt-10 grid grid-cols-2 gap-px bg-primary-foreground/15 lg:grid-cols-4">{([["Mandals Documented",archiveStats.mandals],["Field Photographs",archiveStats.photographs],["Areas of Mumbai",archiveStats.areas],["Heritage Sections",archiveStats.sections]] as const).map(([label,value]) => <div key={label} className="bg-surface-deep p-6 md:p-8"><strong className="font-display text-5xl text-gold-light">{value}</strong><p className="mt-3 text-xs font-bold uppercase tracking-[0.12em] text-primary-foreground/85">{label}</p></div>)}</div></div></section>
    <section className="py-20"><div className="archive-container grid gap-6 lg:grid-cols-2"><div className="archive-card p-7 md:p-10"><ClipboardList className="size-8 text-accent-foreground" /><h2 className="mt-6 font-display text-3xl text-primary md:text-4xl">Community Survey</h2><p className="mt-4 leading-7 text-muted-foreground">Share your views on Mumbai's Ganpati heritage and what should be preserved for future generations.</p><Button asChild className="mt-6"><Link to="/survey">Go to the survey <ArrowRight /></Link></Button></div><div className="archive-card p-7 md:p-10"><Leaf className="size-8 text-accent-foreground" /><h2 className="mt-6 font-display text-3xl text-primary md:text-4xl">Preservation & Awareness</h2><p className="mt-4 leading-7 text-muted-foreground">{preservationSteps.join(" → ")}</p><Button asChild variant="outline" className="mt-6"><Link to="/preservation">How we preserve heritage <ArrowRight /></Link></Button></div></div></section>
  </>;
}
