/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PreservationRouteImport } from './routes/preservation'
import { Route as SurveyRouteImport } from './routes/survey'
import { Route as MandalsMandalIdRouteImport } from './routes/mandals.$mandalId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PreservationRoute = PreservationRouteImport.update({
  id: '/preservation',
  path: '/preservation',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyRoute = SurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const MandalsMandalIdRoute = MandalsMandalIdRouteImport.update({
  id: '/mandals/$mandalId',
  path: '/mandals/$mandalId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contribute': typeof ContributeRoute
  '/explore': typeof ExploreRoute
  '/gallery': typeof GalleryRoute
  '/preservation': typeof PreservationRoute
  '/survey': typeof SurveyRoute
  '/mandals/$mandalId': typeof MandalsMandalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contribute': typeof ContributeRoute
  '/explore': typeof ExploreRoute
  '/gallery': typeof GalleryRoute
  '/preservation': typeof PreservationRoute
  '/survey': typeof SurveyRoute
  '/mandals/$mandalId': typeof MandalsMandalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contribute': typeof ContributeRoute
  '/explore': typeof ExploreRoute
  '/gallery': typeof GalleryRoute
  '/preservation': typeof PreservationRoute
  '/survey': typeof SurveyRoute
  '/mandals/$mandalId': typeof MandalsMandalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contribute'
    | '/explore'
    | '/gallery'
    | '/preservation'
    | '/survey'
    | '/mandals/$mandalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contribute'
    | '/explore'
    | '/gallery'
    | '/preservation'
    | '/survey'
    | '/mandals/$mandalId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contribute'
    | '/explore'
    | '/gallery'
    | '/preservation'
    | '/survey'
    | '/mandals/$mandalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContributeRoute: typeof ContributeRoute
  ExploreRoute: typeof ExploreRoute
  GalleryRoute: typeof GalleryRoute
  PreservationRoute: typeof PreservationRoute
  SurveyRoute: typeof SurveyRoute
  MandalsMandalIdRoute: typeof MandalsMandalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preservation': {
      id: '/preservation'
      path: '/preservation'
      fullPath: '/preservation'
      preLoaderRoute: typeof PreservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey': {
      id: '/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof SurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mandals/$mandalId': {
      id: '/mandals/$mandalId'
      path: '/mandals/$mandalId'
      fullPath: '/mandals/$mandalId'
      preLoaderRoute: typeof MandalsMandalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContributeRoute: ContributeRoute,
  ExploreRoute: ExploreRoute,
  GalleryRoute: GalleryRoute,
  PreservationRoute: PreservationRoute,
  SurveyRoute: SurveyRoute,
  MandalsMandalIdRoute: MandalsMandalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
